### ISSUE TITLE
Password / Session Security

### ISSUE THREAD

**Issue by LukvonStrom** [janburzinski/jbshortener#3]
Hi,
`setcookie('password', md5($password), time() + 24 * 3600, '/');`
Never, I repeat *never* store a hash of the user password on the client side. Instead a JWT or a session id is stored in the cookies/localStorage. This has the benefit of not leaking a unsecure hash to an untrusted party, but instead only storing it in the database while the user is identified using his JWT or his session ID.

MD5 is proven to be unsecure since years, I would reccomend to switch to BCrypt and compare the Hashes via Bcrypt.

For a reference on how to handle Sessions with PHP, follow this tutorial: (https://www.johnmorrisonline.com/build-php-login-form-using-sessions/)

For integrating BCrypt hashing and comparing, follow this StackOverflow answer: (https://stackoverflow.com/a/6337021/5644403)

**Comment by janburzinski** [comment]
Vielen Dank für den Hinweis 👍 
Habs gefixt
